language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allowe_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmpv-dev
  - sudo apt-get install -y mpv
  - sudo apt-get install -y xorg-dev
  - sudo apt-get install -y libxcb-shape0-dev
  - sudo apt-get install -y libxcb-xfixes0-dev
script:
  - cargo build --verbose
